# Generated by Django 5.1.4 on 2025-01-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
