# Generated by Django 5.1.4 on 2025-01-19 10:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alter_jobseeker_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('resume', models.FileField(blank=True, null=True, upload_to='job_seekers/resumes/')),
                ('fathers_name', models.CharField(max_length=20)),
                ('mothers_name', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('address', models.TextField()),
                ('contact_no', models.CharField(blank=True, max_length=11)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobseeker',
        ),
    ]
