# Generated by Django 5.1.5 on 2025-01-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_employerprofile_delete_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
