# Generated by Django 5.1.5 on 2025-01-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone',
            new_name='email',
        ),
    ]
